import product1 from '../assets/images/product1.jpg';
const data = [
  {
    id: 'p-1',
    title: 'عصير تفاح 250مل',
    price: 12,
    stock: 11,
    cal: 112,
    image: product1,
  },
  {
    id: 'p-2',
    title: 'عصير تفاح 250مل',
    price: 12,
    stock: 11,
    cal: 112,
    image: product1,
  },
  {
    id: 'p-3',
    title: 'عصير تفاح 250مل',
    price: 12,
    stock: 11,
    cal: 112,
    image: product1,
  },
  {
    id: 'p-1',
    title: 'عصير تفاح 250مل',
    price: 12,
    stock: 11,
    cal: 112,
    image: product1,
  },
  {
    id: 'p-2',
    title: 'عصير تفاح 250مل',
    price: 12,
    stock: 11,
    cal: 112,
    image: product1,
  },
  {
    id: 'p-3',
    title: 'عصير تفاح 250مل',
    price: 12,
    stock: 11,
    cal: 112,
    image: product1,
  },
  {
    id: 'p-1',
    title: 'عصير تفاح 250مل',
    price: 12,
    stock: 11,
    cal: 112,
    image: product1,
  },
  {
    id: 'p-2',
    title: 'عصير تفاح 250مل',
    price: 12,
    stock: 11,
    cal: 112,
    image: product1,
  },
  {
    id: 'p-3',
    title: 'عصير تفاح 250مل',
    price: 12,
    stock: 11,
    cal: 112,
    image: product1,
  },
  {
    id: 'p-1',
    title: 'عصير تفاح 250مل',
    price: 12,
    stock: 11,
    cal: 112,
    image: product1,
  },
  {
    id: 'p-2',
    title: 'عصير تفاح 250مل',
    price: 12,
    stock: 11,
    cal: 112,
    image: product1,
  },
  {
    id: 'p-3',
    title: 'عصير تفاح 250مل',
    price: 12,
    stock: 11,
    cal: 112,
    image: product1,
  },
  {
    id: 'p-1',
    title: 'عصير تفاح 250مل',
    price: 12,
    stock: 11,
    cal: 112,
    image: product1,
  },
  {
    id: 'p-2',
    title: 'عصير تفاح 250مل',
    price: 12,
    stock: 11,
    cal: 112,
    image: product1,
  },
  {
    id: 'p-3',
    title: 'عصير تفاح 250مل',
    price: 12,
    stock: 11,
    cal: 112,
    image: product1,
  },
  {
    id: 'p-1',
    title: 'عصير تفاح 250مل',
    price: 12,
    stock: 11,
    cal: 112,
    image: product1,
  },
  {
    id: 'p-2',
    title: 'عصير تفاح 250مل',
    price: 12,
    stock: 11,
    cal: 112,
    image: product1,
  },
  {
    id: 'p-3',
    title: 'عصير تفاح 250مل',
    price: 12,
    stock: 11,
    cal: 112,
    image: product1,
  },
  {
    id: 'p-1',
    title: 'عصير تفاح 250مل',
    price: 12,
    stock: 11,
    cal: 112,
    image: product1,
  },
  {
    id: 'p-2',
    title: 'عصير تفاح 250مل',
    price: 12,
    stock: 11,
    cal: 112,
    image: product1,
  },
  {
    id: 'p-3',
    title: 'عصير تفاح 250مل',
    price: 12,
    stock: 11,
    cal: 112,
    image: product1,
  },
  {
    id: 'p-1',
    title: 'عصير تفاح 250مل',
    price: 12,
    stock: 11,
    cal: 112,
    image: product1,
  },
  {
    id: 'p-2',
    title: 'عصير تفاح 250مل',
    price: 12,
    stock: 11,
    cal: 112,
    image: product1,
  },
  {
    id: 'p-3',
    title: 'عصير تفاح 250مل',
    price: 12,
    stock: 11,
    cal: 112,
    image: product1,
  },
];
export default data;
